services:
  db:
    image: postgres:18-alpine
    container_name: wubi-db
    environment:
      POSTGRES_DB: wubi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wubi-api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/wubi
      - PORT=5000
    depends_on:
      - db
    restart: always

  wubi-master:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wubi-master
    ports:
      - "8088:80"
    depends_on:
      - api
    restart: always

volumes:
  pgdata:
