services:
  db:
    image: postgres:18.4
    container_name: wubi-db
    environment:
      POSTGRES_DB: wubi
      POSTGRES_USER: wubi
      POSTGRES_PASSWORD: wubi
    volumes:
      - ./data/postgres:/var/lib/postgresql
    restart: always

  api:
    image: ${API_IMAGE}
    container_name: wubi-api
    environment:
      - DATABASE_URL=postgresql://wubi:wubi@wubi-db:5432/wubi
      - PORT=5000
    depends_on:
      - db
    restart: always

  wubi-master:
    image: ${WEB_IMAGE}
    container_name: wubi-master
    ports:
      - "8000:80"
    restart: always